apiVersion: v2
appVersion: 11.0.3
description: Teleport Operator is a unified access plane for your infrastructure
icon: https://goteleport.com/images/logos/logo-teleport-square.svg
keywords:
- Teleport
name: teleport-operator
version: 11.0.3
