apiVersion: v2
appVersion: 1.3.2
description: A Helm chart for OpenSearch
maintainers:
- name: DandyDeveloper
- name: bbarani
- name: gaiksaya
- name: peterzhuamazon
- name: prudhvigodithi
- name: TheAlgo
name: opensearch
type: application
version: 1.11.1
