# USE THIS CONFIG TO CONFIGURE `route53`` DNS01 CHALLENGE SOLVER
issuer:
  enabled: true
  issuerEmail: <email>  # this is required
  production: true
  # secret is privateKeySecretRef. This private key is used to store the
  # ACME/Let's-Encrypt account private key.
  secret: <secret-name>  # BACKUP THIS SECRET FOR FUTURE USE & SECURITY.
  cloudProvider: route53
  region: us-east-1  # use your own region
  zone: us-east-1a
  hostedZoneID: <hosted-zone-id>
  dnsZones:
    - foo.com
    - bar.com
