apiVersion: v1
kind: ConfigMap
metadata:
  name: teleport-cluster
data:
  teleport.yaml: |
    version: v2
    teleport:
      log:
        severity: INFO
        output: stderr
    auth_service:
      enabled: true
      cluster_name: teleport.obmondo.com
      authentication:
        type: local
        second_factor: on
        u2f:
          app_id: https://teleport.obmondo.com:443
          facets:
          - https://teleport.obmondo.com:443
          - https://teleport.obmondo.com
          - teleport.obmondo.com:443
          - teleport.obmondo.com
      proxy_listener_mode: multiplex
    kubernetes_service:
      enabled: true
      kube_cluster_name: teleport.obmondo.com
      listen_addr: 0.0.0.0:3027
    proxy_service:
      public_addr: 'teleport.obmondo.com:443'
      kube_listen_addr: 0.0.0.0:3026
      enabled: true
      acme:
        enabled: true
        email: ops@enableit.dk
    ssh_service:
      enabled: true
      labels:
        environment: ssh-nodes
