networkpolicies: false
schedule:
  daily: true
  weekly: false
  sixhourly: false
velero:
  configuration:
    logLevel: debug
    features: EnableCSI
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
