---
apiVersion: v1
kind: Service
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-hetzner
  name: caph-webhook-service
  namespace: caph-system
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    cluster.x-k8s.io/provider: infrastructure-hetzner
    control-plane: caph-controller-manager
