
config:
  line-length:
    line_length: 120
    code_blocks: false
    tables: false
  no-bare-urls: false
ignores:
  - 'argocd-helm-charts/*/*/**'
  - 'build/vendor/**'
  - 'build/kube-prometheus/**'
