apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: {{ .Values.customerid }}
  namespace: monitoring-{{ .Values.customerid }}
spec:
  replicas: 1
  resources:
    requests:
      memory: 100Mi
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: alertmanager-config-{{ .Values.customerid }}
