apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config-{{ .Values.customerid }}
  namespace: monitoring-{{ .Values.customerid }}
  labels:
    alertmanagerConfig: {{ .Values.customerid }}
spec:
  route:
    groupBy: ['certname', 'alert_id']
    groupWait: 10s
    groupInterval: 10s
    repeatInterval: 15m
    receiver: 'mattermost'
    routes:
      - receiver: opsmondo
        continue: true
      - receiver: mattermost
        match_re:
          # don't sent watchdog alert in alertmanager
          severity: critical|warning|resolved
        continue: true
  receivers:
  - name: mattermost
    slackConfigs:
      - apiURL:
          key: webhook
          name: slack-webhook
        text: |
        {{ range .Alerts }}
          **Alert:** {{ .Labels.severity }} - {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Hostname:** {{ .Labels.instance }}
        {{ end }}
        sendResolved: true
  - name: opsmondo
    webhookConfigs:
      - url: https://alerts.obmondo.com/hooks/alertmanager
        httpConfig:
          tlsConfig:
            cert:
              key: tls.crt
              name: puppet-agent-tls-auth
            keySecret:
              key: tls.key
              name: puppet-agent-tls-auth
        maxAlerts: 0
        sendResolved: true
