apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config-{{ .Values.customerid }}
  namespace: monitoring-{{ .Values.customerid }}
  labels:
    alertmanagerConfig: alertmanager-config-{{ .Values.customerid }}
spec:
  route:
    groupBy: ['certname', 'alert_id']
    groupWait: 10s
    groupInterval: 10s
    repeatInterval: 15m
    receiver: 'mattermost'
    routes:
      - receiver: ops
        continue: true
      - receiver: mattermost
        match_re:
          # don't sent watchdog alert in alertmanager
          severity: critical|warning|resolved
        continue: true
  receivers:
  - name: mattermost
    slack_configs:
      - api_url: {{ .Values.alertmanager.slack_webhook }}
        text: |-
          {{ range .Alerts }}
            **Alert:** {{ .Labels.severity }} - {{ .Annotations.summary }}
            **Description:** {{ .Annotations.description }}
            **Hostname:** {{ .Labels.instance }}
          {{ end }}
        send_resolved: true
  - name: opsmondo
    webhook_configs:
      - url: https://alerts.obmondo.com/hooks/alertmanager
        send_resolved: true

