apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: grafana-header-{{ .Values.customerid }}
  namespace: monitoring-{{ .Values.customerid }}
spec:
  plugin:
    headerauthentication:
      header:
        key: {{ .Values.customerid }}
        name: X-Obmondo-Customerid
