apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-{{ .Values.customerid }}
  namespace: monitoring-{{ .Values.customerid }}
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.grafana.server }}`)
    priority: 10
    middlewares:
    - name: jwt
      namespace: traefik
    services:
    - kind: Service
      name: grafana-{{ .Values.customerid }}-service
      namespace: monitoring-{{ .Values.customerid }}
      passHostHeader: true
      port: grafana
      nativeLB: true
