apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-{{ .Values.customerid }}
  namespace: monitoring-{{ .Values.customerid }}
  labels:
    dashboards: "grafana"
spec:
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    auth.proxy:
      enabled: "true"
      header_name: "X-WEBAUTH-USER"
      header_property: "username"
      auto_sign_up: "true"
    users:
      allow_sign_up: "false"
      allow_org_create: "false"
      editors_can_admin: "true"
      auto_assign_org: "true"
      auto_assign_org_role: "Editor"
    security:
      allow_embedding: "true"
  dataStorage:
    accessModes:
    - ReadWriteOnce
    size: 1Gi
