apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.customerid }}
  namespace: monitoring-{{ .Values.customerid }}
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.prometheus.server }}`) && Path(`/{{ .Values.customerid }}`)
    priority: 10
    nativeLB: true
    middlewares:
    - name: jwt
      namespace: traefik
    services:
    - kind: Service
      name: prometheus-main
      namespace: monitoring-{{ .Values.customerid }}
      passHostHeader: true
      port: web
  tls:
    options:
      name: prometheus-puppet-agent-tls-auth
      namespace: traefik
