apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ipwhitelist-{{ .Values.customerid }}
  namespace: monitoring-{{ .Values.customerid }}
spec:
  ipWhiteList:
    sourceRange: {{- range .Values.prometheus.ingress.allowedSourceRanges}}
        - {{ . }}
        {{- end}}
