{{- if .Values.prometheusRule.services }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: services-rules
  namespace: monitoring-{{ .Values.customerid }}
spec:
  {{- $.Files.Get "rules/services.yaml" | nindent 4 }}
{{- end }}
