apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ .Values.customerid }}
  namespace: monitoring-{{ .Values.customerid }}
spec:
  externalUrl: /{{ .Values.customerid }}
  routePrefix: /{{ .Values.customerid }}
  evaluationInterval: 30s
  portName: web
  replicas: 1
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: 200m
      memory: 2Gi
  retention: 30d
  scrapeInterval: 30s
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  storage:
    volumeClaimTemplate:
      apiVersion: v1
      kind: PersistentVolumeClaim
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
        storageClassName: rook-ceph-block
  version: v2.43.0
  enableRemoteWriteReceiver: true
