{{- if .Values.prometheusRule.btrfs }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: btrfs-rules
  namespace: monitoring-{{ .Values.customerid }}
spec:
  {{- $.Files.Get "rules/btrfs.yaml" | nindent 4 }}
{{- end }}
