{{- if .Values.prometheusRule.memory }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: memory-rules
  namespace: monitoring-{{ .Values.customerid }}
spec:
  {{- $.Files.Get "rules/memory.yaml" | nindent 4 }}
{{- end }}
