apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ .Values.customerid }}
  namespace: monitoring-{{ .Values.customerid }}
spec:
  podMetadata:
    labels:
      app.kubernetes.io/instance: {{ .Values.customerid }}
      app.kubernetes.io/name: prometheus
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  replicas: 1
  retention: 15d
  ruleNamespaceSelector: {}
  ruleSelector: {}
  externalUrl: /{{ .Values.customerid }}
  routePrefix: /{{ .Values.customerid }}
  evaluationInterval: 30s
  portName: web
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: 200m
      memory: 2Gi
  scrapeInterval: 30s
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  storage:
    volumeClaimTemplate:
      apiVersion: v1
      kind: PersistentVolumeClaim
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
        storageClassName: rook-ceph-block
  version: v2.43.0
  enableRemoteWriteReceiver: true
