{{- if .Values.prometheusRule.disk }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: disk-record-rules
  namespace: monitoring-{{ .Values.customerid }}
spec:
  {{- $.Files.Get "records/disk.yaml" | nindent 4 }}
{{- end }}
