{{- if .Values.prometheusRule.puppet }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: puppet-rules
  namespace: monitoring-{{ .Values.customerid }}
spec:
  {{- $.Files.Get "rules/puppet.yaml" | nindent 4 }}
{{- end }}
