apiVersion: v1
kind: Service
metadata:
  name: prometheus-main
  namespace: monitoring-{{ .Values.customerid }}
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 9090
    targetPort: web
  selector:
    app.kubernetes.io/name: prometheus
  sessionAffinity: ClientIP
