{{- if .Values.prometheusRule.psi }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: psi-record-rules
  namespace: monitoring-{{ .Values.customerid }}
spec:
  {{- $.Files.Get "records/psi.yaml" | nindent 4 }}
{{- end }}
