{{- if .Values.prometheusRule.ssacli }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ssacli-rules
  namespace: monitoring-{{ .Values.customerid }}
spec:
  {{- $.Files.Get "rules/ssacli.yaml" | nindent 4 }}
{{- end }}
