apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ .Values.customerid }}
  namespace: monitoring-{{ .Values.customerid }}
spec:
  alerting:
    alertmanagers:
    - namespace: monitoring-{{ .Values.customerid }}
      name: alertmanager-main
      port: web
  podMetadata:
    labels:
      app.kubernetes.io/instance: {{ .Values.customerid }}
      app.kubernetes.io/name: prometheus
  podMonitorNamespaceSelector: null
  podMonitorSelector: null
  probeNamespaceSelector: null
  probeSelector: null
  replicas: 1
  retention: 15d
  ruleNamespaceSelector: null
  ruleSelector: null
  externalUrl: /{{ .Values.customerid }}
  routePrefix: /{{ .Values.customerid }}
  evaluationInterval: 30s
  portName: web
  resources: {{ toYaml .Values.prometheus.resources | nindent 4 }}
  scrapeInterval: 30s
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  storage:
    volumeClaimTemplate:
      apiVersion: v1
      kind: PersistentVolumeClaim
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
        storageClassName: rook-ceph-block
  version: v2.48.1
  enableRemoteWriteReceiver: true
