apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: oncall-pgsql
spec:
  instances: {{ ((.Values.postgresql).instance) | default 1 }}
  bootstrap:
    initdb:
      database: oncall
      owner: oncall
    recovery:
      backup:
        name: backup-pgsql
  resources:
    limits:
      memory: {{ .Values.postgresql.resources.limits.memory | default "800Mi" }}
      cpu: {{ .Values.postgresql.resources.limits.cpu | default "100m" }}
    requests:
      memory: {{ .Values.postgresql.resources.requests.memory | default "500Mi" }}
      cpu: {{ .Values.postgresql.resources.requests.cpu | default "100m" }}
  storage:
    size: {{ .Values.postgresql.size }}
    {{- if .Values.postgresql.storageClass }}
    storageClass: {{ .Values.postgresql.storageClass }}
    {{- end }}
  backup:
    barmanObjectStore:
      destinationPath: {{ .Values.oncall.backup.destinationPath }}
      {{- if eq .Values.oncall.backup.cloud "aws" }}
      s3Credentials:
        accessKeyId:
          name: oncall-psql-backup-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: oncall-psql-backup-creds
          key: ACCESS_SECRET_KEY
      {{- end }}
      {{- if eq .Values.oncall.backup.cloud "azure" }}
      azureCredentials:
        connectionString:
          name: oncall-psql-backup-creds
          key: AZURE_CONNECTION_STRING
        storageAccount:
          name: oncall-psql-backup-creds
          key: AZURE_STORAGE_ACCOUNT
        storageKey:
          name: oncall-psql-backup-creds
          key: AZURE_STORAGE_KEY
        storageSasToken:
          name: oncall-psql-backup-creds
          key: AZURE_STORAGE_SAS_TOKEN
      {{- end }}
    wal:
      compression: gzip
      encryption: AES256
    retentionPolicy: "30d"
