apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSCluster
metadata:
  name: {{ .Values.global.clusterName }}
  labels:
    cluster.x-k8s.io/name: {{ .Values.global.clusterName }}
spec:
  region: {{ .Values.region }}
  sshKeyName: {{ .Values.sshKeyName }}
  bastion: {{ toYaml .Values.bastion | nindent 4 }}
  network:
    vpc:
      {{- if .Values.vpc.id }}
      id: {{ .Values.vpc.id }}
      {{- else }}
      cidrBlock: {{ .Values.vpc.cidrBlock | default "10.14.0.0/22" }}
      {{- end }}
      availabilityZoneSelection: Ordered
      availabilityZoneUsageLimit: 3
    {{- if .Values.vpc.id }}
    subnets:
      {{- range $index, $subnetID := $.Values.vpc.subnets }}
      - id: {{ $subnetID }}
      {{- end }}
    {{- end }}
    cni:
      cniIngressRules:
        - description: Cilium
          protocol: "tcp"
          fromPort: 4240
          toPort: 4240
        - description: Cilium VXLAN overlay
          protocol: "udp"
          fromPort: 8472
          toPort: 8472
        - description: Cilium health checks
          protocol: "icmp"
          fromPort: 8
          toPort: 8
  controlPlaneLoadBalancer:
    loadBalancerType: {{ .Values.controlPlane.loadBalancer.type }}
    scheme: {{ .Values.controlPlane.loadBalancer.scheme | default "internet-facing" }}
