apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: keycloak-pgsql
spec:
  enableLogicalBackup: true
  databases:
    keycloak: keycloak
  enableMasterLoadBalancer: false
  numberOfInstances: {{ ((.Values.postgresql).instance) | default 1 }}
  postgresql:
    version: "12"
  teamId: keycloak
  users:
    keycloak:
    - superuser
  volume:
    size: 8Gi
