apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: mattermost-pgsql
spec:
  enableLogicalBackup: {{ .Values.postgresql.logicalBackup | default "true" }}
  env:
{{- if .Values.postgresql.access_key_id }}
  - name: AWS_ACCESS_KEY_ID
    value: {{ .Values.postgresql.access_key_id }}
{{- end }}
{{- if .Values.postgresql.access_secret }}
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: {{ .Values.postgresql.access_secret | default "mattermost-pgsql-postgres-pod-env" }}
        key: AWS_SECRET_ACCESS_KEY
{{- end }}
  databases:
    mattermost: mattermost
  enableMasterLoadBalancer: false
  numberOfInstances: {{ ((.Values.postgresql).instance) | default 1 }}
  postgresql:
    version: "12"
  teamId: mattermost
  users:
    mattermost:
    - superuser
  volume:
    size: {{ .Values.postgresql.size }}
    {{- if .Values.postgresql.storageClass }}
    storageClass: {{ .Values.postgresql.storageClass }}
    {{- end }}
  resources:
    limits:
      memory: {{ .Values.postgresql.resources.limits.memory | default "800Mi" }}
      cpu: {{ .Values.postgresql.resources.limits.cpu | default "250m" }}
    requests:
      memory: {{ .Values.postgresql.resources.requests.memory | default "500Mi" }}
      cpu: {{ .Values.postgresql.resources.requests.cpu | default "250m" }}
