apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: mattermost-pgsql
spec:
  databases:
    mattermost: mattermost
  enableMasterLoadBalancer: false
  numberOfInstances: {{ ((.Values.postgresql).instance) | default 1 }}
  postgresql:
    version: "12"
  teamId: mattermost
  users:
    mattermost:
    - superuser
  volume:
    size: {{ .Values.postgresql.size }}
    {{- if .Values.postgresql.storageClass }}
    storageClass: {{ .Values.postgresql.storageClass }}
    {{- end }}
  resources:
    limits:
      memory: {{ .Values.postgresql.resources.limits.memory | default "800Mi" }}
      cpu: {{ .Values.postgresql.resources.limits.cpu | default "250m" }}
    requests:
      memory: {{ .Values.postgresql.resources.requests.memory | default "500Mi" }}
      cpu: {{ .Values.postgresql.resources.requests.cpu | default "250m" }}
