apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: mattermost-pgsql
spec:
  databases:
    keycloak: mattermost
  enableMasterLoadBalancer: false
  numberOfInstances: 2
  postgresql:
    version: "12"
  teamId: mattermost
  users:
    mattermost:
    - superuser
  volume:
    size: 8Gi
