name: kubeaid CI image

"on":
  push:
    branches:
      - main
    paths:
      - '.gitea/Dockerfile'

permissions:
  contents: read

jobs:
  docker-image-build-pull-request:
    uses: Obmondo/gitea-actions/.gitea/workflows/build-image.yaml@main
    with:
      push: true
      context: .gitea
      image_name: obmondo/kubeaid-ci
      tags: 1.2.0
    secrets:
      username: ${{ secrets.HARBOR_USERNAME }}
      password: ${{ secrets.HARBOR_PASSWORD }}
