name: kubeaid CI image

"on":
  push:
    branches:
      - master
    paths:
      - '.gitea/Dockerfile'
      - '.gitea/workflows/container-image.yaml'

permissions:
  contents: read

env:
  KUBEAID_CI_IMAGE: ${{ vars.KUBEAID_CI_IMAGE }}
  KUBEAID_CI_TAG: ${{ vars.KUBEAID_CI_TAG }}

jobs:
  docker-image-build-pull-request:
    runs-on: ubuntu-22.04-htzhel1-ax42-a
    uses: Obmondo/gitea-actions/.gitea/workflows/build-image.yaml@main
    with:
      push: true
      context: .
      file: .gitea/Dockerfile
      tags: ${{ secrets.HARBOR_REGISTRY }}/${{ vars.KUBEAID_CI_IMAGE }}:${{ vars.KUBEAID_CI_TAG }}
    secrets:
      username: ${{ secrets.HARBOR_USERNAME }}
      password: ${{ secrets.HARBOR_PASSWORD }}
