name: kubeaid CI image

on:
  push:
    branches:
      - main
    paths:
      - '.gitea/Dockerfile'

permissions:
  contents: read

env:
  PROJECT_PATH: .gitea
  IMAGE_NAME: obmondo/kubeaid-ci

jobs:
  docker-image-build-pull-request:
    if: github.event_name == 'push'
    uses: Obmondo/gitea-actions/.gitea/workflows/build-image.yaml@main
    with:
      push: true
      context: ${{ env.PROJECT_PATH }}
      tags: 1.2.0
    secrets:
      username: ${{ secrets.HARBOR_USERNAME }}
      password: ${{ secrets.HARBOR_PASSWORD }}
