name: Build and Create Pull Request

"on":
  push:
    branches:
      - main
    paths:
      - "build/**/*"

jobs:
  build_and_create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and Create Pull Request
        run: |
          ./bin/build-and-create-pr.sh
