name: markdownlint

"on":
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  markdownlint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: markdownlint
        uses: https://gitea.obmondo.com/Obmondo/gitea-actions/.gitea/actions/markdownlint-cli2-action@main
        with:
          config: .markdownlint.yaml
          globs: '**/*.md'
