name: shellcheck

"on":
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup shellcheck
      run: |
        apt-get update
        apt-get install shellcheck
        shellcheck --version

    - name: Run shelllcheck
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        find . -type f \( -name *.sh -o -name '*.bash' \) ! \( -path './argocd-helm-charts/*/charts/*' -o -path './build/vendor/*' -o -path './build/kube-prometheus/libraries/*' \) | xargs shellcheck
