name: yamllint

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install yamllint
      run: pip install yamllint

    - name: Run yamllint
      if: ${{ github.event_name == 'pull_request' }}
      run: yamllint --strict --config-file .yamllint .
