apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: keycloakx-pgsql
spec:
  enableLogicalBackup: true
  env:
{{- if .Values.postgresql.access_key_id }}
  - name: AWS_ACCESS_KEY_ID
    value: {{ .Values.postgresql.access_key_id }}
{{- end }}
{{- if .Values.postgresql.access_secret }}
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: {{ .Values.postgresql.access_secret | default "keycloakx-pgsql-postgres-pod-env" }}
        key: AWS_SECRET_ACCESS_KEY
{{- end }}
  databases:
    keycloak: keycloak
  enableMasterLoadBalancer: false
  numberOfInstances: {{ ((.Values.postgresql).instance) | default 1 }}
  postgresql:
    version: "12"
  teamId: keycloakx
  users:
    keycloak:
      - superuser
  volume:
    size: {{ .Values.postgresql.size }}
    {{- if .Values.postgresql.storageClass }}
    storageClass: {{ .Values.postgresql.storageClass }}
    {{- end }}
