apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: keycloakx-pgsql
spec:
  databases:
    keycloak: keycloak
  enableMasterLoadBalancer: false
  numberOfInstances: 2
  postgresql:
    version: "12"
  teamId: keycloakx
  users:
    keycloak:
      - superuser
  volume:
    size: {{ .Values.postgresql.size }}
    {{- if .Values.postgresql.storageClass }}
    storageClass: {{ .Values.postgresql.storageClass }}
    {{- end }}
