{{- if .Values.middleware.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.middleware.name | default "traefik-forward-auth" }}
spec:
  forwardAuth:
    address: http://{{ .Values.middleware.name | default "traefik-forward-auth" }}:4181
    authResponseHeaders:
      - X-Forwarded-User
    trustForwardHeader: true
{{- end }}
