kube-iptables-tailer:
  journalDirectory: "/var/log/journal"
  image:
    repository: honestica/kube-iptables-tailer
    tag: master-100
    pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: obmondo-web-app-gitlab-registry
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
networkpolicies: false
