kube-iptables-tailer:
  journalDirectory: "/var/log/journal"
  calico:
    apiVersion: crd.projectcalico.org/v1
  rbac:
    pspEnabled: false
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
networkpolicies: false
