cloudCredentialsSecretName: cloud-credentials

controlPlane:
  loadBalancer:
    enabled: true
    region: fsn1
  regions:
    - fsn1
  endpoint:
    port: 6443
  replicas: 3

hcloud:
  sshKeyName: kubeaid-demo-hetzner-cluster # Mandatory, even if hcloud.enabled is set to false.

  enabled: true

  controlPlane:
    machineType: cax11

  network:
    zone: eu-central

  nodeGroups: []

robot:
  enabled: false

  sshKeysSecretName: hetzner-robot-ssh-keys

  controlPlane:
    nodes: []

  nodeGroups: []
