mode: hybrid

cloudCredentialsSecretName: cloud-credentials

hcloud:
  zone: eu-central
  imageName: ubuntu-24.04
  sshHKeyPairName: kubeaid-demo

bareMetal:
  sshKeyPairName: kubeaid-demo
  installImage:
    imagePath: /root/.oldroot/nfs/images/Ubuntu-2404-noble-amd64-base.tar.gz

controlPlane:
  regions:
    - fsn1
    - nbg1
    - hel1

  hcloud:
    machineType: cax11
    replicas: 3
    loadBalancer:
      enabled: true
      region: hel1

  bareMetal:

nodeGroups:
  bareMetal: []
  hcloud: []
