cloudCredentialsSecretName: cloud-credentials

hcloudSSHKeyName: kubeaid-demo-hetzner-cluster

hcloud:
  enabled: False
  controlPlane:
    endpoint:
      host: ""
    loadBalancer:
      enabled: true
      region: fsn1
    regions:
      - fsn1
    machineType: cax11
    replicas: 3
  network:
    zone: eu-central
  nodeGroups: []

robot:
  enabled: False
  sshKeysSecretName: hetzner-robot-ssh-keys
  controlPlane:
    endpoint:
      host: ""
    nodes: []
  nodeGroups: []
