cloudCredentialsSecretName: cloud-credentials

# Name of the HCloud SSH Key that ClusterAPI will use to SSH into the nodes.
hcloudSSHKeyName: kubeaid-demo

hcloud:
  enabled: False
  controlPlane:
    endpoint:
      host: ""
    loadBalancer:
      enabled: true
      region: fsn1
    regions:
      - fsn1
    machineType: cax11
    replicas: 3
  network:
    zone: eu-central
  nodeGroups: []

robot:
  enabled: False
  # Name of the Hetzner Robot rescue SSH Key, for the cluster nodes, which ClusterAPI will create
  # and save into a Kubernetes Secret in the cluster.
  rescueSSHKeysSecretsName: kubeaid-demo-hetzner-robot-rescue-ssh-keys
  controlPlane:
    endpoint:
      host: ""
    nodes: []
  nodeGroups: []
