mode: hybrid

cloudCredentialsSecretName: cloud-credentials

zone: eu-central
location: hel1

hcloudSSHKeyPairName: kubeaid-demo
hetznerSSHKeyPairName: kubeaid-demo

network:
  enabled: true

imageName: ubuntu-24.04

installImage:
  imagePath: /root/.oldroot/nfs/images/Ubuntu-2404-noble-amd64-base.tar.gz

controlPlane:
  machineType: cax11
  replicas: 3
  loadBalancer:
    enabled: true
    region: hel1

  regions:
    - fsn1
    - nbg1
    - hel1

nodeGroups:
  bareMetal: []
  hcloud: []
