reloader:
  reloader:
    watchGlobally: true
    reloadOnCreate: true
    serviceMonitor:
      enabled: true
    deployment:
      containerSecurityContext:
        capabilities:
          drop:
            - ALL
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        seccompProfile:
          type: RuntimeDefault
