haproxy:
  # This is necessary to clear the default ports. They cannot be cleared in a
  # cluster value file because of a bug in helm.
  # See https://github.com/helm/helm/issues/9027
  containerPorts:
    http: null
    https: null
    stat: null
