cert-manager:
  podAnnotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  installCRDs: true
  clusterResourceNamespace: cert-manager
  global:
    leaderElection:
      namespace: cert-manager
  prometheus:
    enabled: true
    servicemonitor:
      enabled: true
issuer:
  enabled: false
  production: false
networkpolicies: false
