apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  serviceName: {{ .Values.appName }}
  replicas: 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      terminationGracePeriodSeconds: 10
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3141
              name: webhook1
            - containerPort: 3142
              name: webhook2
          volumeMounts:
            - name: {{ .Values.appName }}
              mountPath: /home/errbot/data
          env:
            {{- toYaml .Values.env | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.appName }}
      spec:
        # ReadWriteOnce means that multiple pods running in only one Node could connect
        # to the storage and carry out read and write operation.
        # However, we will only have 1 pod at a time.
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
