apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant
spec:
  mariaDbRef:
    name: matomo-mariadb
  privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
    - "DROP"
    - "CREATE"
    - "ALTER"
    - "DELETE"
    - "CREATE TEMPORARY TABLES"
  database: "*"
  table: "*"
  username: matomo
  host: "%"
  grantOption: true
  requeueInterval: 30s
  retryInterval: 5s
