apiVersion: mariadb.mmontes.io/v1alpha1
kind: User
metadata:
  name: user
spec:
  name: matomo
  mariaDbRef:
    name: matomo-mariadb
  passwordSecretKeyRef:
    name: mariadb-secret
    key: password
  maxUserConnections: 20
