apiVersion: mariadb.mmontes.io/v1alpha1
kind: Grant
metadata:
  name: grant
spec:
  mariaDbRef:
    name: matomo-mariadb
  privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
    - "DROP"
    - "CREATE"
    - "ALTER"
    - "DELETE"
    - "CREATE TEMPORARY TABLES"
  database: "*"
  table: "*"
  username: matomo
  grantOption: true
