{{ if .Values.networkpolicies }}
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default.default
  namespace: {{ .Release.Namespace }}
spec:
  order: 1000
  types:
  - Ingress
  - Egress
  ingress:
  - action: Log
  - action: Deny
  egress:
  - action: Allow
    protocol: UDP
    destination:
      ports:
      - 53
      namespaceSelector: projectcalico.org/name == 'kube-system'
      selector: k8s-app == 'kube-dns'
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 53
      namespaceSelector: projectcalico.org/name == 'kube-system'
      selector: k8s-app == 'kube-dns'
  - action: Log
  - action: Deny
{{ end }}
