{{- if .Values.policy.RequireRequestCpuMemAndLimitMem }}
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8srequiredresources
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredResources
      validation:
      # Schema for the `parameters` field
        openAPIV3Schema:
          type: object
          properties:
            limits:
              type: array
              description: "A list of limits that should be enforced (cpu, memory or both)."
              items:
                type: string
                enum:
                - memory
            requests:
              type: array
              description: "A list of requests that should be enforced (cpu, memory or both)."
              items:
                type: string
                enum:
                - cpu
                - memory
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |-
        {{ .Files.Get "policies/K8sRequiredResources.rego" | nindent 8 }}
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredResources
metadata:
  name: container-must-have-cpu-requests-memory-limits-and-requests
spec:
  match:
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Pod
    excludedNamespaces:
    {{- range .Values.policy.ExcludedNamespaces }}
    - {{ . | quote }}
    {{- end }}
  parameters:
    limits:
    - memory
    requests:
    - cpu
    - memory
  enforcementAction: {{ .Values.policy.EnforcementAction | default "dryrun" | quote }}
{{- end}}
