prometheus_server: prometheus.obmondo.com
prometheusRule:
  backup: true
  btrfs: true
  cert_expiry: true
  cpu: true
  dellhw: true
  disk: true
  drbd: true
  elasticsearch: true
  file_size: true
  haproxy: true
  iptables: true
  load: true
  lsof: true
  mdraid: true
  memory: true
  monitoring_stack: true
  node_count: true
  ntp: true
  opsmondo: true
  prometheus: true
  psi: true
  puppet: true
  service_gitlab: true
  service_sssd: true
  service_omsagent: true
  services: true
  smart: true
  ssacli: true
