apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-agent-config
  labels:
  {{- include "obmondo-k8s-agent.labels" . | nindent 4 }}
data:
  k8s-agent-config.yaml: |
    endOfLifeURL: "https://endoflife.date/api/kubernetes.json"
    prometheus_url: "http://prometheus-k8s.monitoring:9090"
    api_url: "https://api.obmondo.com"

    # Server Configuration
    server:
      port: 8080
      server_shutdown_timeout: 5s  # in duration format

    # HTTP Client
    http_client:
      http_client_timeout_duration: 30s  # in duration format

    # Kubernetes Metrics
    kube_version:
      fetch_interval: 24h  # in duration format

    # Node Count
    node_count:
      alert_interval: 8h  # in duration format

    # Certificate paths
    agent:
      cert_path: "/opt/obmondo-k8s-agent/tls.crt"
      key_path: "/opt/obmondo-k8s-agent/tls.key"

    argo:
        cron_sync_interval: 2h  # in duration format
        user: ""       # enter either of the user and password or the token
        password: ""
        token: ""
        service_url: "argocd-server.argocd:80"
        white_listed_apps_path: "/opt/obmondo-k8s-agent/white_listed_apps.yaml"
        time_out: 10m  # time to wait before marking a sync as failed
