{{- range $k, $v := .Values.issuer.solvers -}}
{{- if and (eq (toString $v.type) "http") (eq $v.http01.ingress.ingressClassName "traefik-cert-manager") }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: traefik-cert-manager
spec:
  controller: traefik.io/ingress-controller
{{- end }}
{{- end }}
