{{- if and (.Values.issuer.enabled) (not .Values.issuer.name) }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: {{ .Values.issuer.issuerEmail }}
    preferredChain: ""
    privateKeySecretRef:
      name: {{ .Values.issuer.secret }}
    {{ if .Values.issuer.production }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{ else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{ end }}
    solvers:
    - http01:
        ingress:
          class: traefik-cert-manager
{{ end }}

{{- if and (.Values.issuer.enabled) (eq (.Values.issuer.name | toString) "cloudflare") }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: {{ .Values.issuer.issuerEmail }}
    preferredChain: ""
    privateKeySecretRef:
      name: {{ .Values.issuer.secret }}
    {{ if .Values.issuer.production }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{ else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{ end }}
    solvers:
    - dns01:
        cloudflare:
          email: {{ .Values.issuer.issuerEmail }}
          apiTokenSecretRef:
            name: {{ .Values.issuer.secret }}
            key: api-token
{{ end }}
