{{- if .Values.storageClass.enabled -}}

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfspv
parameters:
  recordsize: "4k"
  compression: "off"
  dedup: "off"
  fstype: "zfs"
  poolname: "mypool"
provisioner: zfs.csi.openebs.io

{{- end -}}
