{{- if .Values.storageClass.enabled -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-localpv
parameters:
  recordsize: "4k"
  compression: "off"
  dedup: "off"
  fstype: "zfs"
  poolname: "{{ .Values.storageClass.poolName }}"
provisioner: zfs.csi.openebs.io
{{- if .Values.storageClass.reclaimPolicy }}
reclaimPolicy: {{ toYaml .Values.storageClass.reclaimPolicy }}
{{- end }}
{{- end -}}