{{- if .Values.runner.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.runner.serviceAccount.name }}-ci-admin
  namespace: {{ .Values.runner.nameSpace.name }}
rules:
- apiGroups:
    - ""
    - extensions
    - apps
  resources:
    - '*'
  verbs:
    - '*'
- apiGroups:
    - batch
  resources:
    - jobs
    - cronjobs
  verbs:
    - '*'
- apiGroups:
    - networking.k8s.io
  resources:
    - ingresses
  verbs:
    - get
    - list
    - watch
    - create
    - delete
    - update
    - patch
- apiGroups:
    - acid.zalan.do
  resources:
    - postgresqls
  verbs:
    - '*'
- apiGroups:
    - traefik.io
  resources:
    - middlewares
  verbs:
    - get
    - create
    - delete
- apiGroups:
    - monitoring.coreos.com
  resources:
    - servicemonitors
  verbs:
    - get
    - list
    - watch
    - create
    - delete
    - update
    - patch
{{- end -}}
