{{- if .Values.runner.serviceAccount.create -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ .Values.runner.serviceAccount.name }}-secret
  namespace: {{ .Values.runner.nameSpace.name }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.runner.serviceAccount.name }}
{{- end -}}
