{{- if .Values.runner.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.runner.serviceAccount.name }}
  namespace: {{ .Values.runner.nameSpace.name }}
secrets:
  - name: {{ .Values.runner.serviceAccount.name }}-secret
{{- end -}}
