{{ if .Values.networkpolicies }}
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default.kube-iptables-tailer
spec:
  order: 100
  selector:
    app.kubernetes.io/name == 'kube-iptables-tailer'
  types:
  - Egress
  egress:
  # Allow access to the apiserver
  - action: Allow
    protocol: TCP
    destination:
      selector: kubernetes.io/role == 'master'
      namespaceSelector: global()
      ports:
      - 443
{{- end -}}
