{{- if .Values.backup.enable }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: graylog
  name: opensearch-s3-snapshot-create
spec:
  schedule: {{ .Values.backup.backupSchedule | default "25 05 * * *" | quote }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  startingDeadlineSeconds: 180
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels: {{ .Values.backup.labels | toYaml | nindent 12 }}
        spec:
          volumes:
          - name: s3-credentials
            secret:
              secretName: {{ .Values.backup.secret | default "s3-credentials" }}
          - name: curator-actions
            configMap:
              name: curator-actions-create-snapshot
          containers:
          - name: es-curator
            # 5.8.4 was not working, so sticking it to 5.8.3
            image: {{ .Values.backup.image | default "bitnami/elasticsearch-curator:5.8.3" }}
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - /opt/bitnami/python/bin/curator --config /etc/curator/configs/config.yml /etc/curator/actions/actions.yaml
            volumeMounts:
            - name: s3-credentials
              readOnly: true
              mountPath: "/etc/curator/configs"
            - name: curator-actions
              readOnly: true
              mountPath: "/etc/curator/actions"
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: graylog
  name: opensearch-s3-snapshot-delete
spec:
  schedule: {{ .Values.backup.deleteSchedule | default "20 18 * * *" | quote }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  startingDeadlineSeconds: 180
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels: {{ .Values.backup.labels | toYaml | nindent 12 }}
        spec:
          volumes:
          - name: s3-credentials
            secret:
              secretName: {{ .Values.backup.secret | default "s3-credentials" }}
          - name: curator-actions
            configMap:
              name: curator-actions-delete-snapshot
          containers:
          - name: es-curator
            # 5.8.4 was not working, so sticking it to 5.8.3
            image: {{ .Values.backup.image | default "bitnami/elasticsearch-curator:5.8.3" }}
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - /opt/bitnami/python/bin/curator --config /etc/curator/configs/config.yml /etc/curator/actions/actions.yaml
            volumeMounts:
            - name: s3-credentials
              readOnly: true
              mountPath: "/etc/curator/configs"
            - name: curator-actions
              readOnly: true
              mountPath: "/etc/curator/actions"
          restartPolicy: OnFailure
---
{{- end }}
