# Added features outside upstream chart
middleware:
  jwt:
    enabled: false
    # public_key: <add your pubkey here>

traefik:
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1
  # NOTE: this is to disable the anonymous usage reporting - https://doc.traefik.io/traefik/contributing/data-collection/
  globalArguments: []
  deployment:
    replicas: 2
  logs:
    access:
      enabled: true
  ports:
    websecure:
      tls:
        enabled: true
    web:
      redirectTo: websecure
  experimental:
    plugins:
      enabled: true
  additionalArguments:
    - "--entrypoints.web.proxyprotocol=true"
    - "--entrypoints.web.proxyprotocol.insecure=true"
    - "--entrypoints.websecure.proxyprotocol=true"
    - "--entrypoints.websecure.proxyprotocol.insecure=true"
    - "--experimental.plugins.jwt.moduleName=github.com/team-carepay/traefik-jwt-plugin"
    - "--experimental.plugins.jwt.version=v0.0.13"
  # https://github.com/argoproj/argo-cd/issues/1704#issuecomment-904741817
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
# defines an ingressroute (public url - custom traefik CRD that replaces generic ingress type) for traefik dashboard. Not advised to enable - and below needs addition of a specific url to be accessible.
#  ingressRoute:
#    dashboard:
#      enabled: true
#      annotations:
#        traefik.ingress.kubernetes.io/router.tls: "true"
#        cert-manager.io/cluster-issuer: letsencrypt
