traefik:
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1
  # NOTE: this is to disable the anonymous usage reporting - https://doc.traefik.io/traefik/contributing/data-collection/
  globalArguments: []
  deployment:
    replicas: 2
  logs:
    access:
      enabled: true
  ports:
    websecure:
      tls:
        enabled: true
    web:
      redirectTo: websecure
  additionalArguments:
    - "--entrypoints.web.proxyprotocol=true"
    - "--entrypoints.web.proxyprotocol.insecure=true"
    - "--entrypoints.websecure.proxyprotocol=true"
    - "--entrypoints.websecure.proxyprotocol.insecure=true"
  # https://github.com/argoproj/argo-cd/issues/1704#issuecomment-904741817
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
  ingressRoute:
    dashboard:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: letsencrypt
