{{- if .Values.selfManaged.enabled }}
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  name: {{ .Values.global.clusterName }}-control-plane
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      vmSize: {{ .Values.selfManaged.controlPlane.vmSize }}
      osDisk:
        diskSizeGB: {{ .Values.selfManaged.controlPlane.diskSizeGB }}
        osType: Linux
      sshPublicKey: {{ .Values.sshPublicKey | b64enc }}

---
{{- range $index, $nodeGroup := $.Values.nodeGroups }}
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  name: {{ printf "%s-%s" $.Values.global.clusterName $nodeGroup.name }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      vmSize: {{ $nodeGroup.vmSize }}
      osDisk:
        diskSizeGB: {{ $nodeGroup.diskSizeGB }}
        osType: Linux
      sshPublicKey: {{ .Values.sshPublicKey | b64enc }}
{{- end }}
{{- end }}
