apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  name: {{ .Values.global.clusterName }}-control-plane
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      vmSize: {{ .Values.controlPlane.vmSize }}
      osDisk:
        diskSizeGB: {{ .Values.controlPlane.diskSizeGB }}
        osType: Linux
      dataDisks:
        {{/* Atleast 80GB is recommended.
             REFERENCE : https://etcd.io/docs/v3.4/faq/ */}}
        - diskSizeGB: 80
          lun: 0
          nameSuffix: etcddisk
      networkInterfaces:
        - privateIPConfigs: 110
          subnetName: control-plane
      sshPublicKey: {{ .Values.sshPublicKey | b64enc }}
      identity: UserAssigned
      userAssignedIdentities:
        - providerID: /subscriptions/{{ .Values.subscriptionID }}/resourceGroups/{{ .Values.resourceGroup }}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{{ .Values.userAssignedIdentity }}

---
{{- range $index, $nodeGroup := $.Values.nodeGroups }}
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  name: {{ printf "%s-%s" $.Values.global.clusterName $nodeGroup.name }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      vmSize: {{ $nodeGroup.vmSize }}
      osDisk:
        diskSizeGB: {{ $nodeGroup.diskSizeGB }}
        osType: Linux
      networkInterfaces:
        - privateIPConfigs: 110
          subnetName: node
      sshPublicKey: {{ .Values.sshPublicKey | b64enc }}
{{- end }}
