{{- if .Values.selfmangedCluster }}
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureCluster
metadata:
  name: {{ .Values.global.clusterName }}
  namespace: {{ .Release.Namespace }}
spec:
  location: {{ .Values.location }}
  resourceGroup: {{ .Values.resourceGroup }}
  subscriptionID: {{ .Values.subscriptionID }}
  networkSpec:
    vnet:
      name: {{ .Values.global.virtualNetwork.name }}
      cidrBlocks:
        - {{ .Values.global.virtualNetwork.cidrBlock | toString }}
    subnets:
      - name: {{ .Values.global.virtualNetwork.subnet.name }}
        role: node
        cidrBlocks:
          - {{ .Values.global.virtualNetwork.subnet.cidrBlock | toString }}
{{- end }}
