{{- if .Values.selfManaged.enabled }}
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: {{ .Values.global.clusterName }}-md-0
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      files:
      - contentFrom:
          secret:
            key: sp.json
            name: {{ .Values.selfManaged.clientSecret.workerNode }}
        owner: root:root
        path: /etc/kubernetes/azure.json
        permissions: "0644"
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
          name: '{{ ds.meta_data["local_hostname"] }}'
{{- end }}
