{{ if .Values.networkpolicies }}
---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default.sonarqube-postgresql
  namespace: sonarqube
spec:
  order: 100
  selector:
    application contains 'spilo'
  types:
  - Ingress
  - Egress
  ingress:
  - action: Allow
    protocol: TCP
    source:
      selector: app == 'sonarqube'
    destination:
      ports:
      - 5432 # PostgreSQL
  - action: Allow
    protocol: TCP
    source:
      selector: application contains 'spilo'
    destination:
      ports:
      - 5432 # PostgreSQL
      - 8080 # REST API
  - action: Allow
    protocol: TCP
    source:
      selector: app.kubernetes.io/name == 'postgres-operator'
      namespaceSelector: kubernetes.io/metadata.name == 'postgres-operator'
    destination:
      ports:
      - 5432 # PostgreSQL
      - 8008 # Patroni
  egress:
  # Allow access to the apiserver
  - action: Allow
    protocol: TCP
    destination:
      selector: kubernetes.io/role == 'master'
      namespaceSelector: global()
      ports:
      - 443
  - action: Allow
    protocol: TCP
    destination:
      selector: application contains 'spilo'
      ports:
      - 5432 # PostgreSQL
      - 8080 # REST API
  # Connect to kube2iam
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 8181
      selector: kubernetes.io/role in { 'node', 'master' }
      namespaceSelector: global()
  # S3 endpoint
  # curl https://ip-ranges.amazonaws.com/ip-ranges.json | jq '.prefixes[] | select( .region == "eu-west-1" and .service == "S3" )|.ip_prefix'
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 443
      nets:
      - 3.5.72.0/23
      - 52.218.0.0/17
      - 3.5.64.0/21
      - 52.92.0.0/17
      - 3.251.110.208/28
      - 3.251.110.224/28
---
{{ end }}
