{{ if .Values.networkpolicies }}
---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default.sonarqube-sonarqube
  namespace: sonarqube
spec:
  order: 100
  selector:
    app == 'sonarqube'
  types:
  - Egress
  - Ingress
  egress:
  - action: Allow
    protocol: TCP
    destination:
      selector: application contains 'spilo'
      ports:
      - 5432
  # 199.232.24.209 is pointed to repo1.maven.org
  # Make sure you change when maven guys move their IP :)
  - action: Allow
    protocol: TCP
    destination:
      ports:
        - 443
      nets:
        - 199.232.24.209
  - action: Allow
    protocol: TCP
    destination:
      ports:
        - 443
      nets:
        - 10.5.0.0/16
  # install-plugin is accessing https://github.com
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 443
      nets:
      # curl https://api.github.com/meta | jq -r '.web[]' | grep -v ::
      - 192.30.252.0/22
      - 185.199.108.0/22
      - 140.82.112.0/20
      - 143.55.64.0/20
      - 20.201.28.151/32
      - 20.205.243.166/32
      - 20.87.225.212/32
      - 20.248.137.48/32
      - 20.207.73.82/32
      - 20.27.177.113/32
      - 20.200.245.247/32
      - 20.175.192.147/32
      - 20.233.83.145/32
  ingress:
  - action: Allow
    protocol: TCP
    source:
      selector: app.kubernetes.io/name == 'traefik-public'
      namespaceSelector: kubernetes.io/metadata.name == 'traefik-public'
      nets:
        - 199.232.24.209
    destination:
      ports:
      - 9000
---
{{ end }}
