{{ if .Values.networkpolicies }}
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default.sonarqube-backup-sonarqube-db
  namespace: sonarqube
spec:
  order: 100
  selector:
    app == 'backup-sonarqube-db'
  types:
  - Egress
  egress:
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 5432
      selector: app.kubernetes.io/name == 'postgresql'
  # S3 endpoint
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 443
      nets:
      - 52.218.0.0/16 # AWS S3 is using several IP's in this range
  # Connect to kube2iam
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 8181
{{ end }}
