{{ if .Values.networkpolicies }}
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default.sonarqube-sonarqube
  namespace: sonarqube
spec:
  order: 100
  selector:
    app == 'sonarqube'
  types:
  - Egress
  - Ingress
  egress:
  - action: Allow
    protocol: TCP
    destination:
      selector: application == 'spilo'
      ports:
      - 5432
  # 199.232.24.209 is pointed to repo1.maven.org
  # Make sure you change when maven guys move their IP :)
  - action: Allow
    protocol: TCP
    destination:
      ports:
        - 443
      destination:
        - 199.232.24.209
  ingress:
  - action: Allow
    protocol: TCP
    source:
      selector: app.kubernetes.io/name == 'traefik'
      namespaceSelector: projectcalico.org/name == 'traefik'
      nets:
        - 199.232.24.209
    destination:
      ports:
      - 9000
{{ end }}
