apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: sonarqube-pgsql
  namespace: sonarqube
spec:
  enableLogicalBackup: true
  teamId: sonarqube
  volume:
    size: {{ .Values.postgresql.size }}
    {{- if .Values.postgresql.storageClass }}
    storageClass: {{ .Values.postgresql.storageClass }}
    {{- end }}
  numberOfInstances: 2
  users:
    sonarqube_admin:
      - superuser
      - createdb
    sonarqube_test: []
  databases:
    sonarqube: sonarqube_admin
  postgresql:
    version: "13"
  enableMasterLoadBalancer: false
