apiVersion: v2
appVersion: 11.0.3
dependencies:
- condition: installCRDs,operator.enabled
  name: teleport-operator
  repository: ""
  version: 11.0.3
description: Teleport is a unified access plane for your infrastructure
icon: https://goteleport.com/images/logos/logo-teleport-square.svg
keywords:
- Teleport
name: teleport-cluster
version: 11.0.3
