apiVersion: v2
appVersion: 10.3.1
dependencies:
- condition: installCRDs,operator.enabled
  name: teleport-operator
  repository: ""
  version: 10.3.1
description: Teleport is a unified access plane for your infrastructure
icon: https://goteleport.com/images/logos/logo-teleport-square.svg
keywords:
- Teleport
name: teleport-cluster
version: 10.3.1
