apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: argo-cd
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/name: {{ .Values.global.clusterName }}
  repoURL: https://argoproj.github.io/argo-helm
  chartName: argo-cd
  namespace: argo-cd
  options:
    waitForJobs: true
    wait: true
    timeout: 5m0s
    install:
      createNamespace: true
  configs:
    cmp:
      create: true
      repositories:
        kubeaid-repo:
          name: kubeaid
          type: {{ .Values.cluster.kubeaid.type }}
          url: {{ .Values.cluster.kubeaid.repo }}
        kubeaid-config-repo:
          name: kubeaid-config
          type: {{ .Values.cluster.kubeaidConfig.type }}
          url: {{ .Values.cluster.kubeaidConfig.repo }}
  server:
    initContainers:
    - name: kubeaid-bootstrap-setup
      image: ghcr.io/obmondo/kubeaid-bootstrap-setup:latest
      command:
      - /usr/local/bin/kubeaid-bootstrap-setup
