{{- if (.Values.provider).azure }}
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: ccm-azure-{{ .Values.global.clusterName }}
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/name: {{ .Values.global.clusterName }}
  repoURL: https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/helm/repo
  chartName: cloud-provider-azure
  namespace: kube-system
  releaseName: cloud-provider-azure
  version: 1.30.3
  options:
    waitForJobs: true
    wait: true
    timeout: 5m0s
  valuesTemplate: |
    infra:
      clusterName: {{ .Values.global.clusterName }}
{{- end }}
