apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: cilium-{{ .Values.global.clusterName }}
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/name: {{ .Values.global.clusterName }}
  repoURL: https://helm.cilium.io/
  chartName: cilium
  namespace: cilium
  releaseName: cilium
  version: 1.15.6
  options:
    waitForJobs: true
    wait: true
    timeout: 5m0s
    install:
      createNamespace: true
  valuesTemplate: |
    kubeProxyReplacement: "true"
    k8sServiceHost: {{`{{ .Cluster.spec.controlPlaneEndpoint.host }}`}}
    k8sServicePort: {{`{{ .Cluster.spec.controlPlaneEndpoint.port }}`}}
    ipam:
      mode: "kubernetes"
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
