keycloak:
  postgresql:
    enabled: false
  extraEnv: |
    - name: DB_VENDOR
      value: postgres
    - name: DB_ADDR
      value: keycloak-pgsql
    - name: DB_PORT
      value: "5432"
    - name: DB_DATABASE
      value: keycloak
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: keycloak.keycloak-pgsql.credentials.postgresql.acid.zalan.do
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
        name: keycloak.keycloak-pgsql.credentials.postgresql.acid.zalan.do
        key: password
