keycloakx:
  database:
    vendor: postgres
    hostname: keycloak-pgsql
    port: 5432
    database: keycloak
  extraEnv: |
    - name: KC_DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: keycloak.keycloak-pgsql.credentials.postgresql.acid.zalan.do
          key: username
    - name: KC_DB_PASSWORD
      valueFrom:
        secretKeyRef:
        name: keycloak.keycloak-pgsql.credentials.postgresql.acid.zalan.do
        key: password
