networkpolicies: false
postgres-operator:
  configMajorVersionUpgrade:
    minimal_major_version: "12"
  enableJsonLogging: true
  configKubernetes:
    enable_pod_antiaffinity: true
    enable_pod_disruption_budget: false
