---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerCluster
metadata:
  name: {{ .Values.global.clusterName }}
  labels:
    cluster.x-k8s.io/name: {{ .Values.global.clusterName }}
spec:
  controlPlaneEndpoint:
    host: {{ .Values.controlPlane.endpoint.host }}
    port: {{ .Values.controlPlane.endpoint.port | default 6443 }}
  {{- if .Values.controlPlane.loadBalancer.enabled }}
  controlPlaneLoadBalancer:
    enabled: true
    {{- if .Values.controlPlane.loadBalancer.region }}
    region: {{ .Values.controlPlane.loadBalancer.region }}
    {{- end }}
  {{- end }}
  controlPlaneRegions:
    {{- range .Values.controlPlane.regions }}
    - {{ . | quote }}
    {{- end }}
  {{- if (.Values.hcloud).enabled }}
  hcloudNetwork:
    enabled: true
    networZone: {{ .Values.hcloud.network.zone | default "eu-central" }}
  {{- end }}
  hcloudPlacementGroups:
    - name: control-plane
      type: spread
    {{- range $index, $nodeGroup := ($.Values.hcloud).nodeGroups }}
    - name: {{ $nodeGroup.name }}
      type: spread
    {{- end }}
    {{- range $index, $nodeGroup := ($.Values.robot).nodeGroups }}
    - name: {{ $nodeGroup.name }}
      type: spread
    {{- end }}
  # Reference to a token to be used when reconciling this cluster. This is generated in the
  # security section under API TOKENS.
  # NOTE : Read & write is necessary.
  hetznerSecretRef:
    key:
      hcloudToken: hcloud
      hetznerRobotPassword: robot-password
      hetznerRobotUser: robot-user
    name: {{ .Values.cloudCredentialsSecretName }}
  sshKeys:
    hcloud:
      - name: {{ .Values.hcloud.sshKeyName }}
    robotRescueSecretRef:
      key:
        name: sshkey-name
        privateKey: ssh-privatekey
        publicKey: ssh-publickey
      name: {{ .Values.robot.sshKeysSecretName }}
