---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerCluster
metadata:
  name: {{ .Values.global.clusterName }}
  labels:
    cluster.x-k8s.io/name: {{ .Values.global.clusterName }}
spec:
  {{/* CASE : Control Plane is in Hetzner Bare Metal. The Control Plane endpoint host, should be
               the Failover IP you're using. */}}
  {{- if and ((.Values.robot).enabled) (.Values.controlPlane.endpoint.host) }}
  controlPlaneEndpoint:
    host: {{ .Values.controlPlane.endpoint.host }}
  {{- end }}

  {{/* CASE : Control Plane is in Hetzner Cloud */}}

  {{- if and ((.Values.hcloud).enabled) ((.Values.controlPlane.loadBalancer).enabled) }}
  controlPlaneLoadBalancer:
    enabled: true
    region: {{ .Values.controlPlane.loadBalancer.region }}
  {{- end }}

  controlPlaneRegions:
    {{- range .Values.controlPlane.regions }}
    - {{ . | quote }}
    {{- end }}

  {{/* TODO : Make sure that Control Plane is either in Hetzner Bare Metal or in Hetzner Cloud. */}}


  {{- if (.Values.hcloud).enabled }}
  hcloudNetwork:
    enabled: true
    networZone: {{ .Values.hcloud.network.zone | default "eu-central" }}
  {{- end }}

  hcloudPlacementGroups:
    - name: control-plane
      type: spread

    {{/* For node-groups in Hetzner Cloud. */}}
    {{- range $index, $nodeGroup := ($.Values.hcloud).nodeGroups }}
    - name: {{ $nodeGroup.name }}
      type: spread
    {{- end }}

    {{ /* For node-groups in Hetzner Bare Metal. */ }}
    {{- range $index, $nodeGroup := ($.Values.robot).nodeGroups }}
    - name: {{ $nodeGroup.name }}
      type: spread
    {{- end }}

  # Reference to a token to be used when reconciling this cluster. This is generated in the
  # security section under API TOKENS.
  # NOTE : Read & write is necessary.
  hetznerSecretRef:
    key:
      hcloudToken: hcloud
      hetznerRobotPassword: robot-password
      hetznerRobotUser: robot-user
    name: {{ .Values.cloudCredentialsSecretName }}

  sshKeys:
    hcloud:
      - name: {{ .Values.hcloud.sshKeyName }}
    robotRescueSecretRef:
      key:
        name: sshkey-name
        privateKey: ssh-privatekey
        publicKey: ssh-publickey
      name: {{ .Values.robot.sshKeysSecretName }}
