apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "act_runner.fullname" . }}
  labels:
    {{- include "act_runner.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "act_runner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "act_runner.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "act_runner.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: GITEA_INSTANCE_URL
              value: {{ .Values.act_runner.instance }}
            - name: GITEA_RUNNER_MAX_PARALLEL_JOBS
              value: "2"
            - name: GITEA_RUNNER_LABELS
              value: {{ join "," .Values.act_runner.labels }}
            - name: GITEA_RUNNER_REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  {{- if not .Values.act_runner.existingToken }}
                  name: {{ include "act_runner.fullname" . }}-secret
                  {{- else }}
                  name: {{ .Values.act_runner.existingToken }}
                  {{- end }}
                  key: act-runner-token
          volumeMounts:
            - mountPath: /data
              name: {{ include "act_runner.fullname" . }}-pvc
      volumes:
        - name: {{ include "act_runner.fullname" . }}-pvc
          persistentVolumeClaim:
            claimName: {{ include "act_runner.fullname" . }}-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
