groups:
  - name: monitor::system::service::lsof
    rules:
    - alert: monitor::system::service::lsof::open_deleted_files
      expr: |
        size_of_deleted_open_files > 500 * 1000 * 1000
        and on(certname) obmondo_monitoring{alert_id="monitor::system::service::lsof::open_deleted_files"} > 0
      for: 30m
      labels:
        severity: critical
        alert_id: monitor::system::service::lsof::open_deleted_files
      annotations:
        summary: "Size of open deleted files on **{{ $labels.certname }}** is higher than 500 MB"
        description: "There are large files that are actually deleted but are open in fds and consuming disk space."
