groups:
  - name: 'monitor::service::opsmondo'
    rules:
    - alert: 'monitor::service::opsmondo::alert_without_subscription'
      expr: |
        increase(opsmondo_alert_without_subscription_total[30m]) > 0
        and on (certname) obmondo_monitoring{alert_id="monitor::service::opsmondo::alert_without_subscription"}
      labels:
        severity: warning
        alert_id: 'monitor::service::opsmondo::alert_without_subscription'
      annotations:
        summary: "Server **{{ $labels.certname }}** is sending alerts without subscription"
        description: |+2
          Server {{ $labels.certname }} is sending alerts but has no current
          subscription.

          This can be due to the server getting auto-removed after failing
          Puppet check-in for too long.

    - alert: 'monitor::service::opsmondo::too_few_watchdog_alerts'
      # find times where we have a positive number of watchdog alerts (as these
      # are only positive for obmondomon and customer AlertManager instances)
      # and alert if we see less than one change per 65 minutes.
      #
      # 65 minutes should give us at least 2 watchdog alerts, plus 5 minutes to
      # avoid false positives.
      expr: |
        (changes(opsmondo_watchdog_alerts_total[65m]) < 1)/65*60 and
        opsmondo_watchdog_alerts_total > 0
        and on (certname) obmondo_monitoring{alert_id="monitor::service::opsmondo::too_few_watchdog_alerts"}
      labels:
        severity: warning
        alert_id: 'monitor::service::opsmondo::too_few_watchdog_alerts'
      annotations:
        summary: "Server **{{ $labels.certname }}** has stopped sending watchdog alerts"
        description: |+2
          Server {{ $labels.certname }} have been sending less than 1 watchdog
          alert in the past 65 minutes (current average is {{ .Value }}/hour).

          It could mean that we're no longer accepting watchdog alerts or that
          the client is down.
