groups:
  - name: ZFSStorageAlerts
    rules:
    - alert: HighStorageUsage
      expr: |
        (zfs_pool_size_bytes - zfs_pool_free_bytes) / zfs_pool_size_bytes * 100 >= 85
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "High storage usage on zfs storage pool {{ $labels.pool }}"
        description: "The storage usage on zfs storage {{ $labels.pool }} pool is above 85%. Current usage is {{ $value }}%."
