apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: ccm
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/name: {{ .Values.name }}
  repoURL: https://charts.syself.com
  chartName: ccm-hetzner
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
    install:
      createNamespace: true
    namespace: caph-system
