apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: "{{ .Values.name }}-control-plane-unhealthy-5m"
spec:
  clusterName: {{ .Values.name }}
  maxUnhealthy: 100%
  nodeStartupTimeout: 1h0m0s
  selector:
    matchLabels:
      cluster.x-k8s.io/control-plane: ""
  unhealthyConditions:
    - type: Ready
      status: Unknown
      timeout: 5m0s
    - type: Ready
      status: "False"
      timeout: 5m0s
