rook-ceph-cluster:
  cephBlockPools:
  - name: replicapool
    spec:
      failureDomain: host
      replicated:
        size: 3
        requireSafeReplicaSize: true
    storageClass:
      name: rook-ceph-block
      enabled: true
      isDefault: true
      parameters:
        imageFormat: "2"
        imageFeatures: layering
        csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph  # namespace:cluster
        csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph  # namespace:cluster
        csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
        csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph  # namespace:cluster
        csi.storage.k8s.io/fstype: ext4

  cephClusterSpec:
    monitoring:
      enabled: false
    resources:
      mgr:
        limits: null
      mon:
        limits: null
      osd:
        limits: null
      mgr-sidecar:
        limits: null
      crashcollector:
        limits: null
      logcollector:
        limits: null
      cleanup:
        limits: null

    logCollector:

    disruptionManagement:
      # If true, the operator will create and manage PodDisruptionBudgets for OSD, Mon, RGW, and MDS daemons. OSD PDBs are managed dynamically
      # via the strategy outlined in the [design](https://github.com/rook/rook/blob/master/design/ceph/ceph-managed-disruptionbudgets.md). The operator will
      # block eviction of OSDs by default and unblock them safely when drains are detected.
      managePodBudgets: false
