name: Helm Update

on:
  schedule:
    - cron: '0 0 * * *' # Schedule runs at midnight daily

jobs:
  helm_repo_update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        helm-version: 'v3.8.0'

    - name: Run Helm Repo Update
      if: ${{ github.event_name == 'schedule' }}
      run: |
        ./bin/helm-repo-update.sh --update-all --pull-request --actions --skip-charts argo-cd
