name: Helm Diff

"on":
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'argocd-helm-charts/**/*'

jobs:
  helm-actions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Helm
      run: |
        curl -LO https://get.helm.sh/helm-v3.9.1-linux-amd64.tar.gz
        tar -zxvf helm-v3.9.1-linux-amd64.tar.gz
        mv linux-amd64/helm /usr/local/bin/helm

    - name: Check Helm Version
      run: helm version

    - name: Run helm-diff.sh
      if: ${{ github.event_name == 'pull_request' && !startsWith(github.event.pull_request.title, ':no-diff') }}
      run: |
        export CI_MERGE_REQUEST_TARGET_BRANCH_NAME=${{ github.base_ref }}
        export CI_MERGE_REQUEST_SOURCE_BRANCH_NAME=${{ github.head_ref }}
        chmod +x ./bin/helm-diff.sh
        ./bin/helm-diff.sh
