name: Jsonnet Lint

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  jsonnetlint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run lint-jsonnetfmt.sh
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        chmod +x ./bin/lint-jsonnetfmt.sh
        ./bin/lint-jsonnetfmt.sh
