name: yamllint

"on":
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python3 and Pip3
      run: |
        apt-get update
        apt-get install python3 python3-pip -y
        python3 --version
        pip3 --version

    - name: Install yamllint
      run: python3 -m pip install yamllint

    - name: Run yamllint
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        yamllint --strict --config-file .yamllint .
